"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import Link from "next/link";
import { themes } from "../data/themes";

type Reservation = { id: string; lookup_code: string; theme_title: string; theme_id: string; play_date: string; start_time: string; customer_name: string; phone: string; party_size: number; open_room: boolean; total_amount: number; status: string; payment_status: string };
type Inquiry = { id: string; customer_name: string; phone: string; subject: string; content: string; status: string; response: string | null; created_at: string };
type DashboardData = { metrics: { total: number; active: number; today: number; revenue: number }; reservations: Reservation[]; inquiries: Inquiry[] };

export function AdminDashboard({ userName, userEmail, signOutPath }: { userName: string; userEmail: string; signOutPath: string }) {
  const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); const [tab, setTab] = useState("reservations"); const [busy, setBusy] = useState("");
  const load = useCallback(() => { fetch("/api/admin/dashboard", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); return body; }).then(setData).catch((reason) => setError(reason.message)); }, []);
  useEffect(() => { load(); }, [load]);
  const todayReservations = useMemo(() => data?.reservations.filter((item) => item.play_date === new Date().toLocaleDateString("sv-SE", { timeZone: "Asia/Seoul" })) ?? [], [data]);
  async function patch(url: string, payload: object, key: string) { setBusy(key); setError(""); try { const response = await fetch(url, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "변경하지 못했습니다."); } finally { setBusy(""); } }
  async function createNotice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setBusy("notice"); try { const response = await fetch("/api/admin/notices", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: values.get("title"), content: values.get("content"), pinned: values.get("pinned") === "on" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); form.reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : "공지를 등록하지 못했습니다."); } finally { setBusy(""); } }
  return <main className="admin-shell"><header className="admin-top"><Link className="admin-logo" href="/"><b>CS</b><span>OPERATIONS<br/>CONSOLE</span></Link><div><span>{userName}</span><small>{userEmail}</small><a href={signOutPath}>로그아웃</a></div></header><div className="admin-workspace"><aside className="admin-nav"><p>CASE MANAGEMENT</p>{[["overview", "상황판"], ["reservations", "예약 관리"], ["inquiries", "문의 관리"], ["slots", "회차 관리"], ["notices", "공지 등록"]].map(([value, label], index) => <button key={value} className={tab === value ? "is-active" : ""} onClick={() => setTab(value)}><span>0{index + 1}</span>{label}</button>)}<div><i/>DATABASE LIVE</div></aside><section className="admin-content"><div className="admin-heading"><div><p>CRIME SCENE / ADMIN</p><h1>{tab === "overview" ? "오늘의 상황판" : tab === "reservations" ? "예약 관리" : tab === "inquiries" ? "문의 관리" : tab === "slots" ? "회차 관리" : "공지 등록"}</h1></div><button onClick={() => { setError(""); load(); }}>새로고침</button></div>{error && <p className="admin-error">{error}</p>}{!data && !error && <p className="admin-loading">운영 데이터를 불러오는 중입니다.</p>}{data && tab === "overview" && <><div className="metric-grid"><Metric label="오늘 예약" value={`${data.metrics.today ?? 0}건`} /><Metric label="활성 예약" value={`${data.metrics.active ?? 0}건`} /><Metric label="전체 예약" value={`${data.metrics.total ?? 0}건`} /><Metric label="결제 매출" value={`${Number(data.metrics.revenue ?? 0).toLocaleString()}원`} /></div><AdminTable rows={todayReservations} busy={busy} patch={patch} /></>}{data && tab === "reservations" && <AdminTable rows={data.reservations} busy={busy} patch={patch} />}{data && tab === "inquiries" && <div className="inquiry-admin-list">{data.inquiries.length === 0 && <p className="admin-empty">접수된 문의가 없습니다.</p>}{data.inquiries.map((inquiry) => <InquiryCard key={inquiry.id} inquiry={inquiry} busy={busy} patch={patch} />)}</div>}{tab === "slots" && <SlotManager busy={busy} patch={patch} />}{tab === "notices" && <form className="notice-admin-form" onSubmit={createNotice}><label>공지 제목<input name="title" minLength={2} maxLength={100} required /></label><label>공지 내용<textarea name="content" minLength={5} maxLength={2000} required /></label><label className="admin-check"><input type="checkbox" name="pinned" /> 중요 공지로 상단 고정</label><button disabled={busy === "notice"}>{busy === "notice" ? "등록 중" : "공지 등록"}</button></form>}</section></div></main>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong>{value}</strong><i/></article>; }
function AdminTable({ rows, busy, patch }: { rows: Reservation[]; busy: string; patch: (url: string, payload: object, key: string) => Promise<void> }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>사건 / 일정</th><th>예약자</th><th>인원</th><th>예약 상태</th><th>결제 상태</th><th>저장</th></tr></thead><tbody>{rows.length === 0 && <tr><td colSpan={6}>표시할 예약이 없습니다.</td></tr>}{rows.map((row) => <ReservationRow key={row.id} row={row} busy={busy} patch={patch} />)}</tbody></table></div>; }
function ReservationRow({ row, busy, patch }: { row: Reservation; busy: string; patch: (url: string, payload: object, key: string) => Promise<void> }) { const [status, setStatus] = useState(row.status); const [payment, setPayment] = useState(row.payment_status); return <tr><td><strong>{row.theme_title}</strong><small>{row.play_date} · {row.start_time}<br/>{row.lookup_code}</small></td><td><strong>{row.customer_name}</strong><small>{row.phone}</small></td><td>{row.party_size}명{row.open_room && <small>오픈룸</small>}</td><td><select value={status} onChange={(event) => setStatus(event.target.value)}>{["PENDING_PAYMENT", "CONFIRMED", "COMPLETED", "CANCELED", "NO_SHOW"].map((value) => <option key={value}>{value}</option>)}</select></td><td><select value={payment} onChange={(event) => setPayment(event.target.value)}>{["READY", "PAID", "FAILED", "REFUNDED"].map((value) => <option key={value}>{value}</option>)}</select></td><td><button disabled={busy === row.id} onClick={() => patch("/api/admin/reservations", { id: row.id, status, paymentStatus: payment }, row.id)}>저장</button></td></tr>; }
function InquiryCard({ inquiry, busy, patch }: { inquiry: Inquiry; busy: string; patch: (url: string, payload: object, key: string) => Promise<void> }) { const [status, setStatus] = useState(inquiry.status); const [response, setResponse] = useState(inquiry.response ?? ""); return <article><header><div><span>{inquiry.status}</span><h2>{inquiry.subject}</h2></div><time>{inquiry.created_at.slice(0, 16).replace("T", " ")}</time></header><dl><div><dt>고객</dt><dd>{inquiry.customer_name}</dd></div><div><dt>연락처</dt><dd>{inquiry.phone}</dd></div></dl><p>{inquiry.content}</p><textarea value={response} onChange={(event) => setResponse(event.target.value)} placeholder="운영 답변 메모"/><footer><select value={status} onChange={(event) => setStatus(event.target.value)}>{["NEW", "IN_PROGRESS", "ANSWERED", "CLOSED"].map((value) => <option key={value}>{value}</option>)}</select><button disabled={busy === inquiry.id} onClick={() => patch("/api/admin/inquiries", { id: inquiry.id, status, response }, inquiry.id)}>처리 상태 저장</button></footer></article>; }
function SlotManager({ busy, patch }: { busy: string; patch: (url: string, payload: object, key: string) => Promise<void> }) { const [themeId, setThemeId] = useState("A"); const [date, setDate] = useState(new Date().toLocaleDateString("sv-SE", { timeZone: "Asia/Seoul" })); const theme = themes.find((item) => item.id === themeId)!; return <div className="slot-admin"><div className="slot-controls"><label>사건<select value={themeId} onChange={(event) => setThemeId(event.target.value)}>{themes.map((item) => <option value={item.id} key={item.id}>EP.{item.episode} {item.shortTitle}</option>)}</select></label><label>날짜<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></div><p>선택한 회차를 즉시 예약 가능 또는 운영 중지 상태로 전환합니다.</p><div className="slot-admin-grid">{theme.times.map((time) => <article key={time}><strong>{time}</strong><div><button disabled={busy === time} onClick={() => patch("/api/admin/availability", { themeId, playDate: date, startTime: time, status: "OPEN" }, time)}>OPEN</button><button disabled={busy === time} onClick={() => patch("/api/admin/availability", { themeId, playDate: date, startTime: time, status: "BLOCKED" }, time)}>BLOCK</button></div></article>)}</div></div>; }
