(() => {
  "use strict";

  const API = "https://jhjbiejqtbidloxcwryr.supabase.co/functions/v1/api";
  const PUBLISHABLE_KEY = "sb_publishable_mA5DOfPA-ExloawT3aJpNw_2PeVgEEc";
  const route = document.body.dataset.route || "home";
  const firstSegment = location.pathname.split("/").filter(Boolean)[0];
  const BASE = location.hostname.endsWith("github.io") && firstSegment ? `/${firstSegment}` : "";
  const app = document.querySelector("#app");

  const themes = [
    { id:"A",slug:"orientation",episode:7,title:"크라임씬 EP.7 신입생 오티 살인사건",shortTitle:"신입생 오티 살인사건",tagline:"모두가 같은 밤을 기억하지만, 진술은 서로 다르다.",synopsis:"환영회가 끝난 새벽, 텅 빈 연수원에 남겨진 것은 흩어진 명찰과 끊긴 기억뿐입니다. 가장 가까이 있었던 사람들이 가장 중요한 사실을 숨기고 있습니다.",difficulty:"★★★★☆",players:"4–5명",duration:90,price:23000,image:"theme-orientation.webp",times:["10:00","11:30","13:20","15:10","17:00","18:50","20:40","22:30"] },
    { id:"B",slug:"youtuber",episode:8,title:"크라임씬 EP.8 유튜버 살인사건",shortTitle:"유튜버 살인사건",tagline:"마지막 생방송에서 사라진 12초, 누군가는 편집했다.",synopsis:"생방송이 끊긴 스튜디오. 카메라는 여전히 돌아가고 있지만 결정적인 장면만 사라졌습니다. 구독자에게 공개된 얼굴과 실제 관계 사이에서 진실을 찾아야 합니다.",difficulty:"★★★★☆",players:"4–5명",duration:90,price:23000,image:"theme-youtuber.webp",times:["10:00","11:50","13:40","15:30","17:20","19:10","21:00","22:50"] },
    { id:"C",slug:"hotel",episode:3,title:"크라임씬 EP.3 호텔 살인사건",shortTitle:"호텔 살인사건",tagline:"잠든 듯 발견된 톱 여배우, 객실 열쇠는 하나뿐이었다.",synopsis:"화려한 호텔의 가장 조용한 객실에서 국내 톱 여배우가 숨진 채 발견됩니다. 완벽하게 통제된 동선과 서로 맞지 않는 투숙 기록을 추적하세요.",difficulty:"★★★★★",players:"4–5명",duration:90,price:23000,image:"theme-hotel.webp",times:["10:00","12:10","14:00","15:50","17:40","19:30","21:20","23:10"] },
    { id:"D",slug:"cabin",episode:4,title:"크라임씬 EP.4 산장 살인사건",shortTitle:"산장 살인사건",tagline:"폭설로 고립된 산장, 발자국은 들어왔지만 나가지 않았다.",synopsis:"한밤의 폭설이 모든 길을 지운 뒤 산장 안에서 사건이 발생합니다. 외부인의 흔적은 없고, 출입문은 안에서 잠겨 있었습니다.",difficulty:"★★★★★",players:"4–5명",duration:90,price:23000,image:"theme-cabin.webp",times:["11:00","12:30","14:20","16:10","18:00","19:50","21:40","23:30"] },
  ];

  const h = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
  const money = (value) => `${Number(value || 0).toLocaleString("ko-KR")}원`;
  const reservationStatusLabels = { PENDING_PAYMENT:"접수 완료", CONFIRMED:"예약 확정", COMPLETED:"이용 완료", CANCEL_REQUESTED:"취소 처리 중", CANCELED:"예약 취소", NO_SHOW:"미방문" };
  const paymentStatusLabels = { READY:"결제 대기", PAID:"결제 완료", FAILED:"결제 실패", REFUNDED:"환불 완료" };
  const inquiryStatusLabels = { NEW:"새 문의", IN_PROGRESS:"확인 중", ANSWERED:"답변 완료", CLOSED:"처리 완료" };
  const reservationStatusLabel = (value) => reservationStatusLabels[value] || value;
  const asset = (name) => `${BASE}/images/${name}`;
  const path = (value = "") => `${BASE}/${value}`.replace(/\/$/, value ? "/" : "");
  const arrow = `<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 17 17 7M8 7h9v9" stroke="currentColor" stroke-width="1.5"/></svg>`;
  const formatDate = (value) => new Intl.DateTimeFormat("ko-KR", { year:"numeric",month:"long",day:"numeric",weekday:"short" }).format(new Date(`${value}T12:00:00+09:00`));

  async function api(url, options = {}) {
    const response = await fetch(`${API}${url}`, {
      ...options,
      headers: { apikey:PUBLISHABLE_KEY, "Content-Type":"application/json", ...(options.headers || {}) },
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || "요청을 처리하지 못했습니다.");
    return data;
  }

  function toast(message, type = "") {
    let stack = document.querySelector(".toast-stack");
    if (!stack) { stack = document.createElement("div"); stack.className = "toast-stack"; document.body.append(stack); }
    const node = document.createElement("div"); node.className = `toast ${type}`; node.textContent = message; stack.append(node);
    setTimeout(() => node.remove(), 4500);
  }

  function header(current = "") {
    const nav = [["themes","사건 소개"],["reservations","실시간 예약"],["guide","이용 안내"],["notices","공지사항"],["location","오시는 길"]];
    return `<header class="site-header"><div class="header-inner">
      <a class="brand" href="${path()}" aria-label="크라임씬플레이 서면1호점 홈"><span class="brand-mark"><img src="${BASE}/favicon.svg?v=20260816-3" alt=""></span><span class="brand-copy"><b>CRIME SCENE</b><small>서면1호점 · 리얼 추리게임</small></span></a>
      <nav class="desktop-nav">${nav.map(([slug,label]) => `<a class="${current === slug ? "is-current" : ""}" href="${path(slug)}">${label}</a>`).join("")}</nav>
      <div class="header-actions"><a class="phone-link" href="tel:07043044340"><small>예약 문의</small><strong>070-4304-4340</strong></a><a class="header-book" href="${path("reservations")}">예약하기 ${arrow}</a><button class="menu-button" type="button" aria-label="메뉴 열기"><svg viewBox="0 0 24 24"><path d="M3 7h18M3 12h18M3 17h18" stroke="currentColor"/></svg></button></div>
    </div></header>
    <aside class="mobile-drawer"><div class="drawer-top"><span>전체 메뉴</span><button type="button" aria-label="메뉴 닫기"><svg viewBox="0 0 24 24"><path d="m5 5 14 14M19 5 5 19" stroke="currentColor"/></svg></button></div><nav>${nav.map(([slug,label],i)=>`<a href="${path(slug)}"><span>0${i+1}</span>${label}${arrow}</a>`).join("")}<a href="${path("reservations/lookup")}"><span>06</span>예약 확인·취소${arrow}</a></nav><div class="drawer-contact"><small>서면1호점 예약 문의</small><a href="tel:07043044340">070-4304-4340</a></div></aside>`;
  }

  function footer() {
    return `<footer class="site-footer"><div class="shell footer-top"><div class="footer-brand"><strong>CRIME<br>SCENE</strong><span>서면1호점<br>리얼 추리게임</span></div><div class="footer-links"><div><b>바로가기</b><a href="${path("themes")}">사건 소개</a><a href="${path("reservations")}">실시간 예약</a><a href="${path("location")}">오시는 길</a></div><div><b>고객 안내</b><a href="${path("guide")}">이용 안내</a><a href="${path("notices")}">공지사항</a><a href="${path("faq")}">자주 묻는 질문</a></div><div><b>매장 정보</b><a href="tel:07043044340">070-4304-4340</a><a href="mailto:dbsehrud93@naver.com">dbsehrud93@naver.com</a><span>부산광역시 부산진구 신천대로50번길 62, 4층</span></div></div></div><div class="shell footer-bottom"><p>크라임씬플레이 · 대표 윤호권 · 사업자등록번호 839-87-00850</p><div><a href="${path("policies/terms")}">이용약관</a><a href="${path("policies/privacy")}">개인정보처리방침</a><a href="${path("policies/refunds")}">취소 및 환불 규정</a></div><p>© CRIME SCENE PLAY</p></div></footer>`;
  }

  function pageHero(eyebrow, title, description, className = "") {
    return `<section class="page-hero ${className}"><div class="shell"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div></section>`;
  }

  function homePage() {
    return `${header("home")}<main><section class="hero"><div class="hero-media"></div><div class="hero-grain"></div><div class="shell hero-inner"><div class="hero-copy"><p class="eyebrow"><span>부산 서면 · 역할 몰입형 추리 게임</span></p><h1>당신이 용의자가<br>되는 순간.</h1><p class="hero-lead">사건 속 인물이 되어 현장을 조사하고, 서로의 거짓을 밝혀내세요.<br>정답을 푸는 방탈출을 넘어 한 편의 범죄극을 직접 완성합니다.</p><div class="hero-actions"><a class="button button-primary" href="${path("reservations")}">실시간 예약 ${arrow}</a><a class="button button-ghost" href="${path("themes")}">사건 파일 보기</a></div></div><aside class="hero-dossier"><p class="dossier-label">게임 안내</p><dl><div><dt>이용 시간</dt><dd>90분</dd></div><div><dt>권장 인원</dt><dd>4~5명</dd></div><div><dt>진행 방식</dt><dd>역할 추리</dd></div><div><dt>테마</dt><dd>4개</dd></div></dl></aside></div></section>
    <section class="intro-strip"><div class="shell stat-grid"><div><svg viewBox="0 0 48 48" fill="none"><path d="M10 8h28v32H10zM16 16h16M16 23h16M16 30h9" stroke="currentColor"/></svg><strong>4개의 완성된 사건</strong><span>인물·공간·증거가 유기적으로 연결된 독립 에피소드</span></div><div><svg viewBox="0 0 48 48" fill="none"><circle cx="24" cy="24" r="17" stroke="currentColor"/><path d="M24 14v11l7 4" stroke="currentColor"/></svg><strong>90분의 몰입</strong><span>브리핑부터 현장 조사, 심문과 최종 추리까지</span></div><div><svg viewBox="0 0 48 48" fill="none"><path d="M16 31c0-5 3-8 8-8s8 3 8 8M24 20a5 5 0 1 0 0-10 5 5 0 0 0 0 10ZM10 37h28" stroke="currentColor"/></svg><strong>4–5명의 용의자</strong><span>모든 플레이어가 각자의 비밀과 목적을 가진 주인공</span></div></div></section>
    <section class="section cases-section"><div class="shell"><div class="split-heading"><div class="section-heading"><p class="eyebrow">4개의 독립된 사건</p><h2>봉인된 사건 파일</h2></div><p>사건마다 완전히 다른 인물과 공간, 동기가 기다립니다. 스포일러 없이 제목과 분위기만 확인한 뒤 첫 사건을 선택하세요.</p></div><div class="case-grid">${themes.map((theme,index)=>`<article class="case-card"><a href="${path(`themes/${theme.slug}`)}"><img src="${asset(theme.image)}" alt="${theme.shortTitle}" loading="${index ? "lazy" : "eager"}"><span class="case-shade"></span><b class="case-index">사건 0${index+1}</b><div class="case-content"><p>에피소드 ${theme.episode} · ${theme.duration}분</p><h3>${theme.shortTitle}</h3><span>사건 소개 보기 ${arrow}</span></div></a></article>`).join("")}</div><div class="section-action"><a class="text-link" href="${path("themes")}">모든 사건 비교하기 ${arrow}</a></div></div></section>
    <section class="section experience-section"><div class="shell experience-grid"><div class="experience-title"><p class="eyebrow">방탈출을 넘어선 추리극</p><h2>관찰자가 아닌<br>사건의 당사자로.</h2></div><ol class="experience-list"><li><span>01</span><div><h3>배역을 받아 사건 안으로</h3><p>플레이어 전원이 사건 속 인물이 됩니다. 각자 다른 관계와 비밀을 받은 순간부터 게임은 시작됩니다.</p></div></li><li><span>02</span><div><h3>공간과 소품에서 증거 수집</h3><p>정교하게 구성된 현장을 직접 조사하며 서로의 진술을 검증할 단서를 찾아냅니다.</p></div></li><li><span>03</span><div><h3>심문하고, 설득하고, 추리</h3><p>숨겨야 할 것과 밝혀야 할 것 사이에서 대화하고 마지막에 진범을 지목합니다.</p></div></li></ol></div></section>
    <section class="section reservation-cta"><div class="shell reservation-cta-inner"><div><p class="eyebrow">실시간 예약</p><h2>첫 번째 사건을<br>예약하세요.</h2><p>오늘부터 15일 이내 회차를 실시간으로 확인할 수 있습니다.</p></div><a class="button button-light" href="${path("reservations")}">예약 가능 시간 보기 ${arrow}</a></div></section></main>${footer()}`;
  }

  function themesPage() {
    return `${header("themes")}<main>${pageHero("4개의 사건","사건 소개","각 사건은 독립된 이야기입니다. 원하시는 분위기와 난이도를 기준으로 선택하세요.")}<section class="section theme-list-section"><div class="shell">${themes.map((theme,index)=>`<article class="theme-row"><a class="theme-row-image" href="${path(`themes/${theme.slug}`)}"><img src="${asset(theme.image)}" alt="${theme.shortTitle}"><span>사건 파일 0${index+1}</span></a><div class="theme-row-copy"><p class="eyebrow">에피소드 ${theme.episode}</p><h2>${theme.shortTitle}</h2><blockquote>${theme.tagline}</blockquote><p>${theme.synopsis}</p><dl><div><dt>이용 시간</dt><dd>${theme.duration}분</dd></div><div><dt>권장 인원</dt><dd>${theme.players}</dd></div><div><dt>난이도</dt><dd>${theme.difficulty}</dd></div><div><dt>이용 요금</dt><dd>${money(theme.price)} / 1인</dd></div></dl><div class="row-actions"><a class="button button-primary" href="${path("reservations")}?theme=${theme.id}">예약 시간 보기 ${arrow}</a><a class="text-link" href="${path(`themes/${theme.slug}`)}">사건 상세</a></div></div></article>`).join("")}</div></section></main>${footer()}`;
  }

  function themePage(slug) {
    const theme = themes.find((item)=>item.slug===slug) || themes[0];
    const index = themes.indexOf(theme);
    const next = themes[(index+1)%themes.length];
    return `${header("themes")}<main><section class="theme-detail-hero"><img src="${asset(theme.image)}" alt="${theme.shortTitle}"><div class="theme-detail-overlay"></div><div class="shell theme-detail-copy"><p class="eyebrow">사건 0${index+1} · 에피소드 ${theme.episode}</p><h1>${theme.shortTitle}</h1><blockquote>${theme.tagline}</blockquote><a class="button button-primary" href="${path("reservations")}?theme=${theme.id}">이 사건 예약하기 ${arrow}</a></div><span class="theme-detail-number">0${index+1}</span></section><section class="section theme-brief"><div class="shell theme-brief-grid"><div><p class="eyebrow">스포일러 없는 소개</p><h2>사건 개요</h2><p class="synopsis">${theme.synopsis}</p><p class="spoiler-note">※ 사건의 핵심 정보와 정답을 노출하지 않는 소개입니다.</p></div><aside><div><div class="difficulty-icon">${theme.difficulty}</div><span>난이도</span><strong>추리 난이도</strong></div><div><div class="price-icon">₩</div><span>1인 이용 요금</span><strong>${money(theme.price)}</strong></div><div><span class="difficulty-icon">${theme.duration}</span><span>이용 시간</span><strong>${theme.duration}분</strong></div><div><span class="difficulty-icon">${theme.players}</span><span>이용 인원</span><strong>권장 인원</strong></div></aside></div></section><section class="section detail-process"><div class="shell"><p class="eyebrow">예약 전 확인</p><h2>플레이 전 확인</h2><div class="notice-cards"><article><span>01</span><h3>10분 전 도착</h3><p>배역 배정과 사전 설명을 위해 시작 10분 전까지 도착해 주세요.</p></article><article><span>02</span><h3>스포일러 보안</h3><p>게임 내용과 현장 소품은 촬영하거나 외부에 공개할 수 없습니다.</p></article><article><span>03</span><h3>4–5인 권장</h3><p>4명 미만은 다른 참가자와 함께하는 오픈룸 방식으로 접수됩니다.</p></article></div></div></section><section class="section next-case"><p>다음 사건</p><h2>${next.shortTitle}</h2><a class="button button-light" href="${path(`themes/${next.slug}`)}">다음 사건 보기 ${arrow}</a></section></main>${footer()}`;
  }

  function dateChoices() {
    const today = new Date();
    return Array.from({length:15},(_,index)=>{const date=new Date(today);date.setDate(today.getDate()+index);const value=[date.getFullYear(),String(date.getMonth()+1).padStart(2,"0"),String(date.getDate()).padStart(2,"0")].join("-");return {value,date};});
  }

  function reservationTabs(active) {
    return `<nav class="reservation-tabs"><a class="${active==="board"?"is-active":""}" href="${path("reservations")}">실시간 예약</a><a class="${active==="lookup"?"is-active":""}" href="${path("reservations/lookup")}">예약 확인·취소</a><a href="${path("guide")}">이용 안내</a></nav>`;
  }

  function reservationsPage() {
    const choices=dateChoices(); const params=new URLSearchParams(location.search); const initialTheme=params.get("theme")||"";
    return `${header("reservations")}<main>${pageHero("15일 실시간 예약","실시간 예약","원하는 날짜와 사건을 선택하면 현재 남은 좌석을 바로 확인할 수 있습니다.","reservation-page-hero")}<section class="section reservation-board-section"><div class="shell">${reservationTabs("board")}<div class="reservation-notice"><strong>예약 안내</strong><p>1인 23,000원 · 4–5인 권장 · 4명 미만은 오픈룸 동의가 필요합니다. 회차 시작 24시간 전부터는 온라인 취소가 제한됩니다.</p></div><div class="date-picker"><div class="filter-label"><span>01</span><div><strong>날짜 선택</strong><small>오늘부터 15일</small></div></div><div class="date-scroll">${choices.map(({value,date},index)=>`<button type="button" data-date="${value}" class="${index===0?"is-selected":""}"><small>${index===0?"오늘":new Intl.DateTimeFormat("ko-KR",{weekday:"short"}).format(date)}</small><strong>${date.getDate()}</strong><span>${date.getMonth()+1}월</span></button>`).join("")}</div></div><div class="theme-filter"><div class="filter-label"><span>02</span><div><strong>사건 선택</strong><small>전체 또는 개별 사건</small></div></div><div class="filter-buttons"><button type="button" data-theme="" class="${initialTheme?"":"is-selected"}">전체 사건</button>${themes.map(theme=>`<button type="button" data-theme="${theme.id}" class="${initialTheme===theme.id?"is-selected":""}">${theme.shortTitle}</button>`).join("")}</div></div><div class="schedule-header"><div><span>03</span><h2>예약 가능 회차</h2></div><div class="slot-legend"><span><i class="available"></i>예약 가능</span><span><i class="open"></i>오픈룸</span><span><i></i>마감</span></div></div><div id="schedule"><div class="schedule-state"><span class="loader"></span><p>실시간 회차를 확인하고 있습니다.</p></div></div></div></section></main>${footer()}`;
  }

  async function initReservations() {
    let selectedDate=dateChoices()[0].value;
    let selectedTheme=new URLSearchParams(location.search).get("theme")||"";
    const schedule=document.querySelector("#schedule");
    async function load(){
      schedule.innerHTML=`<div class="schedule-state"><span class="loader"></span><p>실시간 회차를 확인하고 있습니다.</p></div>`;
      try{
        const data=await api(`/availability?date=${selectedDate}${selectedTheme?`&theme=${selectedTheme}`:""}`);
        schedule.innerHTML=`<div class="schedule-list">${data.themes.map(theme=>`<article class="schedule-theme"><div class="schedule-theme-info"><img src="${asset(theme.image.split("/").pop())}" alt=""><div><small>사건 ${theme.id}</small><h3>${h(theme.shortTitle)}</h3><p>90분 · 1인 23,000원</p></div></div><div class="time-grid">${theme.times.map(slot=>{const available=slot.status==="OPEN"&&slot.remaining>0;const open=available&&slot.openRoom;return available?`<a class="time-slot ${open?"is-open":"is-available"}" href="${path("reservations/new")}?theme=${theme.id}&date=${selectedDate}&time=${slot.time}"><strong>${slot.time}</strong><span>${open?`오픈룸 · ${slot.remaining}석 남음`:`예약 가능 · ${slot.remaining}석`}</span>${arrow}</a>`:`<div class="time-slot is-disabled"><strong>${slot.time}</strong><span>${slot.status==="BLOCKED"?"운영 중지":"예약 마감"}</span></div>`}).join("")}</div></article>`).join("")}</div>`;
      }catch(error){schedule.innerHTML=`<div class="schedule-state error"><strong>회차를 불러오지 못했습니다.</strong><p>${h(error.message)}</p><button type="button">다시 시도</button></div>`;schedule.querySelector("button")?.addEventListener("click",load);}
    }
    document.querySelectorAll("[data-date]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-date]").forEach(node=>node.classList.remove("is-selected"));button.classList.add("is-selected");selectedDate=button.dataset.date;load();}));
    document.querySelectorAll("[data-theme]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-theme]").forEach(node=>node.classList.remove("is-selected"));button.classList.add("is-selected");selectedTheme=button.dataset.theme;load();}));
    load();
  }

  function reservationNewPage() {
    const params=new URLSearchParams(location.search);const theme=themes.find(item=>item.id===params.get("theme"));const date=params.get("date");const time=params.get("time");
    if(!theme||!date||!time||!theme.times.includes(time)) return `${header("reservations")}<main>${pageHero("Reservation form","예약 정보 입력","선택한 사건과 회차를 확인해 주세요.","form-page-hero")}<section class="section reservation-form-section"><div class="shell invalid-selection"><h2>예약할 회차가 선택되지 않았습니다.</h2><a class="button button-primary" href="${path("reservations")}">실시간 예약으로 돌아가기</a></div></section></main>${footer()}`;
    return `${header("reservations")}<main>${pageHero("예약 정보 입력","예약 정보 입력","예약자 정보와 필수 동의를 확인하면 접수가 완료됩니다.","form-page-hero")}<section class="section reservation-form-section"><div class="shell booking-layout"><aside class="booking-summary"><img src="${asset(theme.image)}" alt="${theme.shortTitle}"><div class="booking-summary-copy"><p class="eyebrow">선택한 사건</p><h2>${theme.shortTitle}</h2><dl><div><dt>일정</dt><dd>${formatDate(date)}</dd></div><div><dt>회차</dt><dd>${time}</dd></div><div><dt>이용 시간</dt><dd>${theme.duration}분</dd></div><div><dt>기본 금액</dt><dd>${money(theme.price)} / 1인</dd></div></dl><a href="${path("reservations")}">회차 다시 선택</a></div></aside><form id="booking-form" class="booking-form"><div class="form-heading"><span>01</span><div><h2>예약자 정보</h2><p>예약 확인과 운영 안내에 사용됩니다.</p></div></div><div class="field-grid"><label><span>예약자 이름 <i>필수</i></span><input name="customerName" maxlength="20" autocomplete="name" required></label><label><span>휴대폰 번호 <i>필수</i></span><input name="phone" inputmode="tel" autocomplete="tel" placeholder="010-0000-0000" required></label></div><div class="form-heading second"><span>02</span><div><h2>이용 인원</h2><p>4명 미만은 다른 참가자와 함께하는 오픈룸으로 접수됩니다.</p></div></div><div class="party-picker">${[1,2,3,4,5].map(size=>`<button type="button" data-size="${size}" class="${size===4?"is-selected":""}"><strong>${size}</strong><span>명</span></button>`).join("")}</div><label class="open-room-option"><input type="checkbox" name="openRoom"><span class="custom-check"></span><div><strong>오픈룸 참여에 동의합니다.</strong><p>1–3명 예약 시 필수이며 다른 플레이어와 함께 사건을 진행합니다.</p></div></label><label class="textarea-field"><span>요청 사항</span><textarea name="specialRequest" maxlength="300" placeholder="매장에 전달할 내용이 있다면 입력해 주세요."></textarea><small>최대 300자</small></label><div class="price-summary"><span>결제 예정 금액</span><strong id="total-price">${money(theme.price*4)}</strong><small>1인 ${money(theme.price)} × <span id="party-count">4</span>명</small></div><div class="payment-note"><strong>온라인 카드 결제 준비 중</strong><p>현재 예약은 접수 상태로 저장되며 결제 방법은 매장에서 안내드립니다.</p></div><div class="consent-list"><label><input type="checkbox" name="privacyConsent" required><span>[필수] 개인정보 수집 및 이용에 동의합니다.</span><a href="${path("policies/privacy")}" target="_blank">내용 보기</a></label><label><input type="checkbox" name="cancellationConsent" required><span>[필수] 취소 및 환불 규정을 확인했습니다.</span><a href="${path("policies/refunds")}" target="_blank">내용 보기</a></label></div><div id="booking-message"></div><button class="submit-booking" type="submit"><span>예약 접수하기</span><strong id="submit-price">${money(theme.price*4)}</strong>${arrow}</button></form></div></section></main>${footer()}`;
  }

  function initReservationNew(){
    const form=document.querySelector("#booking-form");if(!form)return;const params=new URLSearchParams(location.search);const theme=themes.find(item=>item.id===params.get("theme"));let partySize=4;
    const update=()=>{document.querySelector("#total-price").textContent=money(theme.price*partySize);document.querySelector("#submit-price").textContent=money(theme.price*partySize);document.querySelector("#party-count").textContent=partySize;const option=form.querySelector(".open-room-option");if(partySize<4){option.classList.add("is-selected");option.querySelector("input").checked=true}else option.classList.toggle("is-selected",option.querySelector("input").checked);};
    form.querySelectorAll("[data-size]").forEach(button=>button.addEventListener("click",()=>{form.querySelectorAll("[data-size]").forEach(node=>node.classList.remove("is-selected"));button.classList.add("is-selected");partySize=Number(button.dataset.size);update();}));form.openRoom.addEventListener("change",update);
    form.addEventListener("submit",async(event)=>{event.preventDefault();const submit=form.querySelector("button[type=submit]");const message=form.querySelector("#booking-message");submit.disabled=true;message.innerHTML="";const data=Object.fromEntries(new FormData(form));try{const result=await api("/reservations",{method:"POST",body:JSON.stringify({themeId:theme.id,playDate:params.get("date"),startTime:params.get("time"),customerName:data.customerName,phone:data.phone,partySize,openRoom:form.openRoom.checked,specialRequest:data.specialRequest,privacyConsent:form.privacyConsent.checked,cancellationConsent:form.cancellationConsent.checked})});sessionStorage.setItem("crimescene-last-reservation",JSON.stringify(result));location.href=path("reservations/complete");}catch(error){message.innerHTML=`<p class="form-message">${h(error.message)}</p>`;submit.disabled=false;}});
  }

  function reservationCompletePage(){
    let result=null;try{result=JSON.parse(sessionStorage.getItem("crimescene-last-reservation"));}catch{}const reservation=result?.reservation;
    if(!reservation)return `<main class="complete-section"><div class="complete-card"><h1>예약 정보를 찾을 수 없습니다.</h1><p class="complete-lead">예약 확인 페이지에서 이름과 휴대폰 번호로 다시 조회할 수 있습니다.</p><div class="complete-actions"><a class="button button-primary" href="${path("reservations/lookup")}">예약 확인</a><a class="button button-ghost" href="${path()}">홈으로</a></div></div></main>`;
    return `<main class="complete-section"><div class="complete-card"><span class="complete-seal">접수<br>완료</span><p class="eyebrow">예약 접수 완료</p><h1>예약이 접수되었습니다.</h1><p class="complete-lead">예약 확인과 취소는 예약자 이름과 휴대폰 번호로 간편하게 이용할 수 있습니다.</p><dl><div><dt>사건</dt><dd>${h(reservation.themeTitle)}</dd></div><div><dt>일정</dt><dd>${formatDate(reservation.playDate)}</dd></div><div><dt>회차</dt><dd>${h(reservation.startTime)}</dd></div><div><dt>인원</dt><dd>${reservation.partySize}명</dd></div><div><dt>결제 예정</dt><dd>${money(reservation.totalAmount)}</dd></div><div><dt>접수 상태</dt><dd>접수 완료</dd></div></dl><div class="payment-state"><strong>온라인 카드 결제 준비 중</strong><p>결제 방법은 매장에서 안내드립니다.</p></div><div class="complete-actions"><a class="button button-primary" href="${path("reservations/lookup")}">예약 확인하기</a><a class="button button-ghost" href="${path()}">홈으로</a></div></div></main>`;
  }

  function reservationLookupPage(){
    return `${header("reservations")}<main>${pageHero("예약 내역 조회","예약 확인·취소","예약자 이름과 휴대폰 번호로 접수 내역을 확인할 수 있습니다.","lookup-page-hero")}<section class="section lookup-section"><div class="shell lookup-shell">${reservationTabs("lookup")}<div class="lookup-layout"><div class="lookup-copy"><p class="eyebrow">간편 조회</p><h2>예약 정보를<br>입력해 주세요.</h2><p>예약할 때 입력한 이름과 휴대폰 번호가 일치하는 최근 예약을 최대 10건까지 표시합니다.</p></div><div><form id="lookup-form" class="lookup-form"><label><span>예약자 이름</span><input name="customerName" autocomplete="name" required></label><label><span>휴대폰 번호</span><input name="phone" inputmode="tel" autocomplete="tel" required></label><button type="submit">예약 조회</button><div id="lookup-feedback"></div></form><div id="lookup-results"></div></div></div></div></section></main>${footer()}`;
  }

  function renderLookupResults(reservations,formData){
    const host=document.querySelector("#lookup-results");if(!reservations.length){host.innerHTML=`<p class="lookup-feedback">일치하는 예약이 없습니다.</p>`;return;}host.innerHTML=`<div class="lookup-results"><div class="results-heading"><strong>예약 내역</strong><span>${reservations.length}건</span></div>${reservations.map(item=>`<article class="reservation-result"><div class="result-main"><span class="status-badge status-${String(item.status).toLowerCase()}">${h(reservationStatusLabel(item.status))}</span><h3>${h(item.themeTitle)}</h3><dl><div><dt>일정</dt><dd>${formatDate(item.playDate)} ${h(item.startTime)}</dd></div><div><dt>인원</dt><dd>${item.partySize}명</dd></div><div><dt>연락처</dt><dd>${h(item.phoneMasked)}</dd></div><div><dt>금액</dt><dd>${money(item.totalAmount)}</dd></div></dl></div>${!["CANCELED","CANCEL_REQUESTED","COMPLETED"].includes(item.status)?`<button class="cancel-reservation" type="button" data-cancel="${h(item.lookupCode)}">예약 취소</button>`:""}</article>`).join("")}</div>`;host.querySelectorAll("[data-cancel]").forEach(button=>button.addEventListener("click",async()=>{if(!confirm("이 예약을 취소하시겠습니까? 이용 24시간 전부터는 온라인 취소가 제한됩니다."))return;button.disabled=true;try{const data=await api("/reservations/cancel",{method:"POST",body:JSON.stringify({lookupCode:button.dataset.cancel,customerName:formData.customerName,phone:formData.phone,reason:"고객 온라인 취소"})});toast(data.message);document.querySelector("#lookup-form").requestSubmit();}catch(error){toast(error.message,"error");button.disabled=false;}}));
  }

  function initReservationLookup(){const form=document.querySelector("#lookup-form");form?.addEventListener("submit",async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));const feedback=form.querySelector("#lookup-feedback");feedback.innerHTML=`<div class="loading-bar"></div>`;try{const result=await api("/reservations/lookup",{method:"POST",body:JSON.stringify(data)});feedback.innerHTML="";renderLookupResults(result.reservations,data);}catch(error){feedback.innerHTML=`<p class="lookup-feedback error">${h(error.message)}</p>`;}});}

  function guidePage(){return `${header("guide")}<main>${pageHero("처음 방문하시는 분께","이용 안내","처음이어도 괜찮습니다. 필요한 내용은 입장 전 모두 안내해 드립니다.")}<section class="section guide-section"><div class="shell guide-intro"><div><p class="eyebrow">크라임씬플레이란?</p><h2>각자 용의자가 되어<br>진짜 범인을 찾는 추리게임</h2></div><p>살인사건 현장에서 플레이어는 저마다 비밀을 가진 인물이 됩니다. 현장을 조사하고 증거를 수집한 뒤 서로의 진술을 검증해 다섯 명 중 진범을 찾아내는 역할 몰입형 게임입니다.</p></div><div class="shell guide-steps"><article><span>01</span><h3>예약 및 도착</h3><p>실시간 시간표에서 원하는 사건을 예약하고 시작 10분 전까지 매장에 도착합니다.</p></article><article><span>02</span><h3>배역 브리핑</h3><p>사건 속 인물과 관계, 개인 정보를 확인합니다. 내용은 다른 사람에게 보여주지 않습니다.</p></article><article><span>03</span><h3>현장 조사</h3><p>제한된 시간 동안 공간과 소품을 살피며 사건에 필요한 증거를 모읍니다.</p></article><article><span>04</span><h3>심문과 추리</h3><p>발견한 단서로 서로를 추궁하고 최종적으로 가장 의심스러운 인물을 지목합니다.</p></article></div></section><section class="section caution-section"><div class="shell"><div><p class="eyebrow">방문 전 확인</p><h2>주의사항</h2></div><ul><li><strong>보안</strong><p>게임 속 내용과 소품은 촬영하거나 외부에 공개할 수 없습니다. 입장 전 휴대폰을 보관합니다.</p></li><li><strong>안전</strong><p>폐쇄된 공간에서 진행됩니다. 폐쇄공포증이 있거나 음주 상태, 임신 중인 경우 이용을 권하지 않습니다.</p></li><li><strong>연령</strong><p>15세 이하 이용은 제한될 수 있습니다. 미성년자 이용 가능 여부는 예약 전 매장으로 확인해 주세요.</p></li><li><strong>CCTV</strong><p>안전과 콘텐츠 보안을 위해 게임 공간에 CCTV가 설치되어 있습니다.</p></li></ul></div></section><section class="section guide-cta"><div class="shell"><h2>이제 사건을 선택하세요.</h2><a class="button button-light" href="${path("reservations")}">실시간 예약 ${arrow}</a></div></section></main>${footer()}`;}

  function noticesPage(){return `${header("notices")}<main>${pageHero("매장 운영 안내","공지사항","예약과 매장 운영에 필요한 최신 안내를 확인하세요.","support-page-hero")}<section class="section support-section"><div class="shell support-layout"><aside><span>등록된 공지</span><strong id="notice-count">—</strong><p>중요 공지는 상단에 고정됩니다.<br>방문 전 최신 내용을 확인해 주세요.</p></aside><div id="notice-list"><div class="support-loading"><div class="loading-bar"></div></div></div></div></section></main>${footer()}`;}
  async function initNotices(){const host=document.querySelector("#notice-list");try{const data=await api("/notices");document.querySelector("#notice-count").textContent=String(data.notices.length).padStart(2,"0");host.innerHTML=`<div class="notice-list">${data.notices.map(notice=>`<article><div><span>${notice.pinned?"중요 공지":"공지"}</span><time>${new Intl.DateTimeFormat("ko-KR").format(new Date(notice.created_at))}</time></div><h2>${h(notice.title)}</h2><p>${h(notice.content)}</p></article>`).join("")}</div>`;}catch(error){host.innerHTML=`<p class="support-error">${h(error.message)}</p>`;}}

  function faqPage(){const faqs=[["몇 명이 가장 재미있나요?","모든 사건은 4–5인을 권장합니다. 1–3명 예약은 다른 참가자와 함께하는 오픈룸으로 운영됩니다."],["플레이 시간은 얼마나 걸리나요?","게임은 약 90분이며 배역 배정과 사전 설명을 위해 시작 10분 전까지 도착해 주세요."],["처음 해도 참여할 수 있나요?","가능합니다. 입장 전 진행 방식과 규칙을 충분히 안내하며, 특별한 추리 경험이 없어도 참여할 수 있습니다."],["온라인 예약을 취소할 수 있나요?","예약 확인·취소 페이지에서 가능합니다. 다만 이용 24시간 전부터는 온라인 취소가 제한되므로 매장으로 문의해 주세요."],["촬영이 가능한가요?","콘텐츠 보안을 위해 게임 공간과 소품 촬영은 불가능합니다. 안내된 포토존은 이용할 수 있습니다."]];return `${header("guide")}<main>${pageHero("이용 전 확인하세요","자주 묻는 질문","이용 전 궁금한 내용을 확인하거나 매장에 직접 문의하세요.","support-page-hero")}<section class="section support-section"><div class="shell faq-layout"><div class="faq-list">${faqs.map((item,index)=>`<details ${index===0?"open":""}><summary><span>0${index+1}</span>${item[0]}<i>+</i></summary><p>${item[1]}</p></details>`).join("")}</div><aside class="inquiry-panel"><p class="eyebrow">일대일 문의</p><h2>문의 접수</h2><p>연락처와 내용을 남겨 주시면 확인 후 안내드립니다.</p><form id="inquiry-form"><label><span>이름</span><input name="customerName" required></label><label><span>휴대폰 번호</span><input name="phone" inputmode="tel" required></label><label><span>제목</span><input name="subject" maxlength="100" required></label><label><span>문의 내용</span><textarea name="content" minlength="10" maxlength="2000" required></textarea></label><label class="inquiry-consent"><input type="checkbox" name="privacyConsent" required><span>개인정보 수집 및 이용에 동의합니다.</span></label><div id="inquiry-message"></div><button type="submit">문의 접수하기</button></form></aside></div></section></main>${footer()}`;}
  function initInquiry(){const form=document.querySelector("#inquiry-form");form?.addEventListener("submit",async(event)=>{event.preventDefault();const button=form.querySelector("button");const message=form.querySelector("#inquiry-message");button.disabled=true;const data=Object.fromEntries(new FormData(form));try{const result=await api("/inquiries",{method:"POST",body:JSON.stringify({...data,privacyConsent:form.privacyConsent.checked})});message.innerHTML=`<p class="support-success">${h(result.message)}</p>`;form.reset();}catch(error){message.innerHTML=`<p class="support-error">${h(error.message)}</p>`;}finally{button.disabled=false;}});}

  function locationPage(){return `${header("location")}<main>${pageHero("서면1호점 위치 안내","오시는 길","지도에서 정확한 매장 위치와 주변 경로를 확인하실 수 있습니다.")}<section class="section location-section"><div class="shell location-grid"><div class="location-map"><iframe title="크라임씬플레이 서면1호점 지도" src="https://www.google.com/maps?q=%EB%B6%80%EC%82%B0%EA%B4%91%EC%97%AD%EC%8B%9C%20%EB%B6%80%EC%82%B0%EC%A7%84%EA%B5%AC%20%EC%8B%A0%EC%B2%9C%EB%8C%80%EB%A1%9C50%EB%B2%88%EA%B8%B8%2062&z=17&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-address"><strong>크라임씬플레이 서면1호점</strong><span>부전동 우성빌딩 4층</span></div></div><div class="location-copy"><p class="eyebrow">크라임씬플레이 서면1호점</p><h2>서면1호점</h2><dl><div><dt>주소</dt><dd>부산광역시 부산진구 신천대로50번길 62<br>부전동 우성빌딩 4층</dd></div><div><dt>예약 문의</dt><dd><a href="tel:07043044340">070-4304-4340</a></dd></div><div><dt>운영</dt><dd>회차별 예약 운영<br>첫 회차 10:00 · 마지막 회차 23:30</dd></div><div><dt>도착 시간</dt><dd>배역 배정과 사전 설명을 위해<br>예약 10분 전까지 도착</dd></div></dl><div class="location-actions"><a class="button button-primary" href="https://map.naver.com/p/search/%EB%B6%80%EC%82%B0%20%EB%B6%80%EC%82%B0%EC%A7%84%EA%B5%AC%20%EC%8B%A0%EC%B2%9C%EB%8C%80%EB%A1%9C50%EB%B2%88%EA%B8%B8%2062" target="_blank" rel="noreferrer">네이버 지도 열기 ${arrow}</a><a class="button" href="tel:07043044340">전화 문의</a></div></div></div></section><section class="section arrival-tips"><div class="shell"><p class="eyebrow">방문 전 확인</p><h2>방문 전 확인</h2><div><article><span>01</span><h3>대중교통</h3><p>서면역 2번 출구에서 도보 약 8분 거리이며 삼정타워 인근에 있습니다.</p></article><article><span>02</span><h3>시간 엄수</h3><p>게임 시작 후에는 배역 설명과 진행 흐름 때문에 중도 입장이 어렵습니다. 10분 전 도착을 권장합니다.</p></article><article><span>03</span><h3>주차 확인</h3><p>도심 매장 특성상 주차 가능 여부가 달라질 수 있으므로 차량 방문 전 매장으로 문의해 주세요.</p></article></div></div></section></main>${footer()}`;}

  const policies={
    terms:{eyebrow:"서비스 이용 기준",title:"이용약관",intro:"크라임씬플레이 서비스 이용에 관한 기본 조건입니다.",sections:[["제1조 목적","본 약관은 크라임씬플레이가 제공하는 예약 및 체험 서비스 이용과 관련하여 사업자와 이용자 사이의 권리·의무 및 책임사항을 정함을 목적으로 합니다."],["제2조 예약의 성립","이용자가 예약 정보를 제출하고 사업자가 접수를 확인한 때 예약이 성립합니다. 온라인 카드 결제 활성화 이후에는 결제 승인이 완료되어야 예약이 확정됩니다."],["제3조 이용자 의무","이용자는 정확한 예약 정보를 제공하고, 안전 수칙과 콘텐츠 보안 정책을 준수해야 합니다. 고의적인 시설 훼손이나 스포일러 공개로 발생한 손해에 책임이 따를 수 있습니다."],["제4조 서비스 제한","음주 상태, 안전상 위험이 예상되는 상태 또는 운영 방침을 현저히 위반하는 경우 이용이 제한될 수 있습니다."]]},
    privacy:{eyebrow:"개인정보 보호 안내",title:"개인정보처리방침",intro:"예약 운영에 필요한 최소한의 개인정보만 수집하고 안전하게 처리합니다.",sections:[["수집 항목","예약자 이름, 휴대폰 번호, 예약 사건·일정·인원, 이용자가 직접 입력한 요청 사항을 수집합니다. 문의 접수 시 이름, 연락처, 제목 및 문의 내용을 수집합니다."],["이용 목적","예약 확인·변경·취소, 결제 처리, 매장 운영 안내, 문의 답변 및 분쟁 대응을 위해 사용합니다."],["보유 기간","예약 및 결제 정보는 관계 법령상 보존 의무가 있는 기간 동안 보유한 뒤 파기합니다. 단순 문의 정보는 처리 완료 후 운영 정책에 따라 안전하게 파기합니다."],["안전성 확보 조치","휴대폰 번호는 전송 구간에서 암호화하며 예약 정보는 외부에 공개되지 않도록 접근 권한을 제한해 보관합니다."],["문의","개인정보 관련 문의: dbsehrud93@naver.com / 070-4304-4340"]]},
    refunds:{eyebrow:"예약 취소 안내",title:"취소 및 환불 규정",intro:"예약 변경 및 취소 시 아래 기준이 적용됩니다.",sections:[["온라인 취소","이용 시작 24시간 전까지 예약 확인·취소 페이지에서 접수할 수 있습니다. 결제 완료 예약은 결제 취소 확인 후 최종 처리됩니다."],["24시간 이내 취소","이용 시작 24시간 전부터는 온라인 취소가 제한됩니다. 매장으로 직접 문의해 주세요. 환불 가능 여부는 실제 결제 시점에 고지된 기준과 관계 법령을 따릅니다."],["지각 및 노쇼","지각 시 전체 이용 시간이 줄어들 수 있으며, 시작 후에는 중도 입장이 제한될 수 있습니다. 연락 없는 미방문은 환불이 제한될 수 있습니다."],["매장 사유 취소","시설 또는 운영상의 사유로 체험을 제공할 수 없는 경우 일정 변경 또는 전액 환불을 안내합니다."]]},
  };
  function policyPage(kind){const data=policies[kind]||policies.terms;return `${header("guide")}<main>${pageHero(data.eyebrow,data.title,data.intro,"policy-page-hero")}<section class="section policy-section"><div class="shell policy-layout"><aside><b>약관 및 정책</b><a href="${path("policies/terms")}">이용약관</a><a href="${path("policies/privacy")}">개인정보처리방침</a><a href="${path("policies/refunds")}">취소 및 환불 규정</a><small>최종 수정일: 2026년 8월 16일</small></aside><article>${data.sections.map(([title,content])=>`<h2>${title}</h2><p>${content}</p>`).join("")}</article></div></section></main>${footer()}`;}

  const adminStore={token:localStorage.getItem("crimescene-admin-token")||"",user:null,data:null,view:"overview"};
  async function adminApi(url,options={}){return api(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${adminStore.token}`}});}
  function adminPage(){return `<div id="admin-root" class="admin-shell"><div class="boot-screen"><span>크라임씬플레이 서면1호점</span><i></i><small>운영 관리 화면을 불러오는 중</small></div></div>`;}
  function renderAdminLogin(message=""){
    document.querySelector("#admin-root").innerHTML=`<main class="admin-login-page"><section class="admin-login-card"><span class="red">관리자 전용</span><h1>운영 관리</h1><p>예약·결제·문의·회차 운영 데이터를 관리합니다. 관리자 암호키를 입력해 주세요. 5회 이상 실패하면 15분 동안 시도가 제한됩니다.</p><form id="admin-login"><label class="field"><span>관리자 암호키</span><input type="password" name="accessKey" autocomplete="current-password" autocapitalize="none" spellcheck="false" autofocus required></label>${message?`<p class="admin-error">${h(message)}</p>`:""}<button type="submit">관리 화면 열기</button><small>입력한 암호키는 안전하게 확인되며 화면에 표시되지 않습니다.</small></form><p><a href="${BASE==="/crimescene-admin"?"https://sosirusok.github.io/crimescene/":path()}">← 고객 사이트로 이동</a></p></section></main>`;
    document.querySelector("#admin-login").addEventListener("submit",async(event)=>{event.preventDefault();const button=event.currentTarget.querySelector("button");button.disabled=true;const values=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api("/admin/login",{method:"POST",body:JSON.stringify(values)});adminStore.token=result.token;adminStore.user=result.user;localStorage.setItem("crimescene-admin-token",result.token);await loadAdmin();}catch(error){renderAdminLogin(error.message);}});
  }
  function adminLayout(content,title,subtitle){
    const items=[["overview","대시보드"],["reservations","예약 관리"],["inquiries","문의 관리"],["slots","회차 관리"],["notices","공지 등록"]];
    return `<header class="admin-top"><a class="admin-logo" href="${BASE==="/crimescene-admin"?"https://sosirusok.github.io/crimescene/":path()}"><img src="${BASE}/favicon.svg?v=20260816-3" alt=""><span>서면1호점<br>운영 관리</span></a><div><span>${h(adminStore.user?.displayName||"서면점 운영자")}</span><small>크라임씬플레이 서면1호점</small><a href="#" id="admin-logout">로그아웃</a></div></header><div class="admin-workspace"><nav class="admin-nav"><p>운영 메뉴</p>${items.map(([key,label],index)=>`<button type="button" data-admin-view="${key}" class="${adminStore.view===key?"is-active":""}"><span>0${index+1}</span>${label}</button>`).join("")}<div><i></i>데이터 연결됨</div></nav><main class="admin-content"><header class="admin-heading"><div><p>${subtitle}</p><h1>${title}</h1></div><button type="button" id="admin-refresh">새로고침</button></header><div id="admin-view">${content}</div></main></div>`;
  }
  function metricsHtml(metrics){const items=[["전체 예약",metrics.total,"건"],["유효 예약",metrics.active,"건"],["오늘 예약",metrics.today,"건"],["결제 매출",Number(metrics.revenue).toLocaleString("ko-KR"),"원"]];return `<section class="metric-grid">${items.map(([label,value,unit])=>`<article><span>${label}</span><strong>${value}<small>${unit}</small></strong><i></i></article>`).join("")}</section>`;}
  function reservationTable(rows){if(!rows.length)return `<p class="admin-empty">예약 데이터가 없습니다.</p>`;return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>내부 접수 ID</th><th>사건 / 일정</th><th>예약자</th><th>인원 / 금액</th><th>예약 상태</th><th>결제 상태</th><th>처리</th></tr></thead><tbody>${rows.map(row=>`<tr data-reservation-row="${row.id}"><td><strong>${h(row.lookup_code)}</strong><small>${new Date(row.created_at).toLocaleString("ko-KR")}</small></td><td><strong>${h(row.theme_title)}</strong><small>${h(row.play_date)} · ${h(row.start_time)}</small></td><td><strong>${h(row.customer_name)}</strong><small>${h(row.phone)}</small></td><td><strong>${row.party_size}명</strong><small>${money(row.total_amount)} · ${row.open_room?"오픈룸":"단독"}</small></td><td><select data-field="status">${["PENDING_PAYMENT","CONFIRMED","COMPLETED","CANCELED","NO_SHOW"].map(value=>`<option value="${value}" ${row.status===value?"selected":""}>${reservationStatusLabels[value]}</option>`).join("")}</select></td><td><select data-field="paymentStatus">${["READY","PAID","FAILED","REFUNDED"].map(value=>`<option value="${value}" ${row.payment_status===value?"selected":""}>${paymentStatusLabels[value]}</option>`).join("")}</select></td><td><button type="button" data-save-reservation>저장</button></td></tr>`).join("")}</tbody></table></div>`;}
  function inquiriesHtml(rows){if(!rows.length)return `<p class="admin-empty">접수된 문의가 없습니다.</p>`;return `<div class="inquiry-admin-list">${rows.map(row=>`<article data-inquiry="${row.id}"><header><div><span>${h(inquiryStatusLabels[row.status]||row.status)}</span><h2>${h(row.subject)}</h2></div><time>${new Date(row.created_at).toLocaleString("ko-KR")}</time></header><dl><div><dt>이름</dt><dd>${h(row.customer_name)}</dd></div><div><dt>연락처</dt><dd>${h(row.phone)}</dd></div></dl><p>${h(row.content)}</p><textarea data-inquiry-response placeholder="답변 메모">${h(row.response||"")}</textarea><footer><select data-inquiry-status>${["NEW","IN_PROGRESS","ANSWERED","CLOSED"].map(value=>`<option value="${value}" ${row.status===value?"selected":""}>${inquiryStatusLabels[value]}</option>`).join("")}</select><button type="button" data-save-inquiry>문의 저장</button></footer></article>`).join("")}</div>`;}
  function noticeAdminHtml(){return `<form id="admin-notice-form" class="notice-admin-form"><label><span>공지 제목</span><input name="title" maxlength="100" required></label><label><span>공지 내용</span><textarea name="content" maxlength="4000" required></textarea></label><label class="admin-check"><input type="checkbox" name="pinned">상단 고정 공지로 등록</label><div id="admin-form-message"></div><button type="submit">공지 게시</button></form>`;}
  async function slotsHtml(){const today=dateChoices()[0].value;return `<div class="slot-controls"><label>운영 날짜<input type="date" id="slot-date" value="${today}"></label><label>사건<select id="slot-theme">${themes.map(theme=>`<option value="${theme.id}">${theme.shortTitle}</option>`).join("")}</select></label></div><div id="slot-admin-list"><div class="admin-loading">회차 상태를 불러오는 중입니다.</div></div>`;}
  async function loadSlots(){const host=document.querySelector("#slot-admin-list");if(!host)return;const date=document.querySelector("#slot-date").value;const themeId=document.querySelector("#slot-theme").value;host.innerHTML=`<div class="admin-loading">회차 상태를 불러오는 중입니다.</div>`;try{const data=await api(`/availability?date=${date}&theme=${themeId}`);const theme=data.themes[0];host.innerHTML=`<div class="slot-admin-grid">${theme.times.map(slot=>`<article><strong>${slot.time}</strong><p>${slot.bookedCount}/${slot.capacity}명 · ${slot.openRoom?"오픈룸":"일반"}</p><div><button type="button" data-slot="${slot.time}" data-status="OPEN">운영</button><button type="button" data-slot="${slot.time}" data-status="BLOCKED">중지</button></div></article>`).join("")}</div>`;host.querySelectorAll("[data-slot]").forEach(button=>button.addEventListener("click",async()=>{button.disabled=true;try{await adminApi("/admin/availability",{method:"PATCH",body:JSON.stringify({themeId,playDate:date,startTime:button.dataset.slot,status:button.dataset.status})});toast("회차 상태를 변경했습니다.");await loadSlots();}catch(error){toast(error.message,"error");button.disabled=false;}}));}catch(error){host.innerHTML=`<p class="admin-error">${h(error.message)}</p>`;}}
  async function renderAdminView(){const data=adminStore.data;let content="",title="",subtitle="";if(adminStore.view==="overview"){title="운영 대시보드";subtitle="오늘 운영 현황";content=metricsHtml(data.metrics)+reservationTable(data.reservations.slice(0,10));}else if(adminStore.view==="reservations"){title="예약 관리";subtitle="예약 접수 및 상태 관리";content=reservationTable(data.reservations);}else if(adminStore.view==="inquiries"){title="문의 관리";subtitle="고객 문의 및 답변 관리";content=inquiriesHtml(data.inquiries);}else if(adminStore.view==="slots"){title="회차 관리";subtitle="사건별 운영 회차 관리";content=await slotsHtml();}else if(adminStore.view==="notices"){title="공지 등록";subtitle="고객 사이트 공지 게시";content=noticeAdminHtml();}else{adminStore.view="overview";title="운영 대시보드";subtitle="오늘 운영 현황";content=metricsHtml(data.metrics)+reservationTable(data.reservations.slice(0,10));}document.querySelector("#admin-root").innerHTML=adminLayout(content,title,subtitle);bindAdmin();if(adminStore.view==="slots")loadSlots();}
  function bindAdmin(){
    document.querySelector("#admin-logout")?.addEventListener("click",event=>{
      event.preventDefault();
      localStorage.removeItem("crimescene-admin-token");
      adminStore.token="";
      renderAdminLogin();
    });
    document.querySelector("#admin-refresh")?.addEventListener("click",loadAdmin);
    document.querySelectorAll("[data-admin-view]").forEach(button=>button.addEventListener("click",()=>{
      adminStore.view=button.dataset.adminView;
      renderAdminView();
    }));
    document.querySelectorAll("[data-save-reservation]").forEach(button=>button.addEventListener("click",async()=>{
      const row=button.closest("tr");
      button.disabled=true;
      try{
        await adminApi("/admin/reservations",{method:"PATCH",body:JSON.stringify({id:row.dataset.reservationRow,status:row.querySelector('[data-field="status"]').value,paymentStatus:row.querySelector('[data-field="paymentStatus"]').value})});
        toast("예약 상태를 저장했습니다.");
        await loadAdmin();
      }catch(error){toast(error.message,"error");button.disabled=false;}
    }));
    document.querySelectorAll("[data-save-inquiry]").forEach(button=>button.addEventListener("click",async()=>{
      const card=button.closest("[data-inquiry]");
      button.disabled=true;
      try{
        await adminApi("/admin/inquiries",{method:"PATCH",body:JSON.stringify({id:card.dataset.inquiry,status:card.querySelector("[data-inquiry-status]").value,response:card.querySelector("[data-inquiry-response]").value})});
        toast("문의 상태를 저장했습니다.");
        await loadAdmin();
      }catch(error){toast(error.message,"error");button.disabled=false;}
    }));
    document.querySelector("#slot-date")?.addEventListener("change",loadSlots);
    document.querySelector("#slot-theme")?.addEventListener("change",loadSlots);
    document.querySelector("#admin-notice-form")?.addEventListener("submit",async(event)=>{
      event.preventDefault();
      const form=event.currentTarget;
      const values=Object.fromEntries(new FormData(form));
      try{
        await adminApi("/admin/notices",{method:"POST",body:JSON.stringify({...values,pinned:form.pinned.checked})});
        form.reset();
        form.querySelector("#admin-form-message").innerHTML=`<p class="support-success">공지를 게시했습니다.</p>`;
      }catch(error){form.querySelector("#admin-form-message").innerHTML=`<p class="admin-error">${h(error.message)}</p>`;}
    });
  }
  async function loadAdmin(){try{adminStore.data=await adminApi("/admin/dashboard");if(!adminStore.user)adminStore.user={displayName:"서면점 운영자",role:"OWNER"};await renderAdminView();}catch(error){if(/로그인/.test(error.message)){localStorage.removeItem("crimescene-admin-token");adminStore.token="";renderAdminLogin("세션이 만료되었습니다. 암호키를 다시 입력해 주세요.");}else document.querySelector("#admin-root").innerHTML=`<main class="admin-login-page"><div class="admin-error">${h(error.message)}</div></main>`;}}
  function initAdmin(){if(!adminStore.token)renderAdminLogin();else loadAdmin();}

  function notFoundPage(){return `<main class="not-found"><strong>404</strong><h1>사건 파일을 찾을 수 없습니다.</h1><p>주소가 변경되었거나 존재하지 않는 페이지입니다.</p><a class="button button-primary" href="${path()}">홈으로 돌아가기</a></main>`;}

  const renderers={home:homePage,themes:themesPage,reservations:reservationsPage,"reservation-new":reservationNewPage,"reservation-complete":reservationCompletePage,"reservation-lookup":reservationLookupPage,guide:guidePage,notices:noticesPage,faq:faqPage,location:locationPage,admin:adminPage,"not-found":notFoundPage};
  let html="";
  if(route.startsWith("theme:"))html=themePage(route.split(":")[1]);else if(route.startsWith("policy:"))html=policyPage(route.split(":")[1]);else html=(renderers[route]||notFoundPage)();
  app.innerHTML=html;
  document.querySelector(".menu-button")?.addEventListener("click",()=>document.querySelector(".mobile-drawer")?.classList.add("is-open"));
  document.querySelector(".mobile-drawer button")?.addEventListener("click",()=>document.querySelector(".mobile-drawer")?.classList.remove("is-open"));
  addEventListener("scroll",()=>document.querySelector(".site-header")?.classList.toggle("is-solid",scrollY>40),{passive:true});
  if(route==="reservations")initReservations();
  if(route==="reservation-new")initReservationNew();
  if(route==="reservation-lookup")initReservationLookup();
  if(route==="notices")initNotices();
  if(route==="faq")initInquiry();
  if(route==="admin")initAdmin();
})();
